apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame-extractor-web-deployment
  labels: 
    app: frame-extractor-web-deployment
  annotations:
    author: Grupo 51 - Fiap Postech - 7SOAT
    app-version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frame-extractor-web
  template:
    metadata:
      labels:
        app: frame-extractor-web
    spec:
      containers:
        - name: frame-extractor-web
          image: arterodocker/frame-extractor-portal:1.0.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m